//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXIM.Portal.WebParts.CONTROLTEMPLATES.Exim.InvitationForm.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvitationForm_ascx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvitationForm_ascx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXIM.Portal.WebParts.CONTROLTEMPLATES.Exim.InvitationForm.App_LocalResources.Invi" +
                            "tationForm.ascx", typeof(InvitationForm_ascx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم.
        /// </summary>
        internal static string btnSubmit_text {
            get {
                return ResourceManager.GetString("btnSubmit.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الاتصال.
        /// </summary>
        internal static string formTitle_text {
            get {
                return ResourceManager.GetString("formTitle.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/Invitation/Lists/Registrations.
        /// </summary>
        internal static string InvitationArListURL {
            get {
                return ResourceManager.GetString("InvitationArListURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/Invitation.
        /// </summary>
        internal static string InvitationArSiteURL {
            get {
                return ResourceManager.GetString("InvitationArSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل.
        /// </summary>
        internal static string lblCompanyName_text {
            get {
                return ResourceManager.GetString("lblCompanyName.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string lblEmail_text {
            get {
                return ResourceManager.GetString("lblEmail.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنصب / المسمى الوظيفي.
        /// </summary>
        internal static string lblJobTitle_text {
            get {
                return ResourceManager.GetString("lblJobTitle.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string lblMobileNumber_text {
            get {
                return ResourceManager.GetString("lblMobileNumber.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string lblName_text {
            get {
                return ResourceManager.GetString("lblName.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success, Thank you for subscribing to the forum.
        /// </summary>
        internal static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل مطلوب .
        /// </summary>
        internal static string RequiredField_text {
            get {
                return ResourceManager.GetString("RequiredField.text", resourceCulture);
            }
        }
    }
}
