//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXIM.Portal.WebParts.CONTROLTEMPLATES.Exim.ProductConsultant.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FindMyProduct_ascx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FindMyProduct_ascx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXIM.Portal.WebParts.CONTROLTEMPLATES.Exim.ProductConsultant.App_LocalResources.F" +
                            "indMyProduct.ascx", typeof(FindMyProduct_ascx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الخدمة المناسبة.
        /// </summary>
        internal static string btn_Submit_Text {
            get {
                return ResourceManager.GetString("btn_Submit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلب الخدمة الان.
        /// </summary>
        internal static string hypr_RequestService_Text {
            get {
                return ResourceManager.GetString("hypr_RequestService.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الخدمة.
        /// </summary>
        internal static string hypr_ServiceDetails_Text {
            get {
                return ResourceManager.GetString("hypr_ServiceDetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف تصف منشأتك؟.
        /// </summary>
        internal static string lbl_Benificiary_Text {
            get {
                return ResourceManager.GetString("lbl_Benificiary.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل اخرى.
        /// </summary>
        internal static string lbl_OtherDetails_Text {
            get {
                return ResourceManager.GetString("lbl_OtherDetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتج المناسب لك:.
        /// </summary>
        internal static string lbl_Result_Text {
            get {
                return ResourceManager.GetString("lbl_Result.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما الذي تبحث عنه؟.
        /// </summary>
        internal static string lbl_Usage_Text {
            get {
                return ResourceManager.GetString("lbl_Usage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ملء البيانات التالية حتى نتمكن من مساعدتك في اختيار المنتج الأنسب لك من بين الخدمات التي يقدمها البنك..
        /// </summary>
        internal static string lbl_UserInstruction_Text {
            get {
                return ResourceManager.GetString("lbl_UserInstruction.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/Services/.
        /// </summary>
        internal static string Product_ConsultantArSiteURL {
            get {
                return ResourceManager.GetString("Product-ConsultantArSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/Services/Lists/ProductConsultant.
        /// </summary>
        internal static string Product_ConsultantListRelativeURL {
            get {
                return ResourceManager.GetString("Product-ConsultantListRelativeURL", resourceCulture);
            }
        }
    }
}
